bootstrap.servers=kafka:9092
group.id=ledgersync-connect
listeners=http://0.0.0.0:8083
rest.advertised.host.name=connect
rest.advertised.port=8083

config.storage.topic=ledgersync.connect.configs
offset.storage.topic=ledgersync.connect.offsets
status.storage.topic=ledgersync.connect.status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
offset.storage.partitions=1
status.storage.partitions=1
offset.flush.interval.ms=1000

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
plugin.path=/kafka/connect

producer.max.request.size=1048576
producer.buffer.memory=8388608
consumer.max.partition.fetch.bytes=1048576
consumer.fetch.max.bytes=4194304
